### ISSUE TITLE
jest 28/29 support

### ISSUE THREAD

**Issue by oteoe** [preactjs/jest-preset-preact#16]
when is the release with jest 29 support planned 0 its already in master ?

**Comment by oteoe** [comment]
it's merged 3 months ago ...

**Comment by rschristian** [comment]
There's still this (rather large) issue: https://github.com/preactjs/jest-preset-preact/pull/13#issuecomment-1403785276

I'd suggest to keep using older versions of Jest if possible.

**Comment by mdeperas** [comment]
The installation of the jest-preset-preact complains about jest dependency aboce @27. Is there any workaround for that?

**Comment by rschristian** [comment]
Besides adhering to the peerDependency range and using v27? Not really.

**Comment by mdeperas** [comment]
Thanks a lot

**Comment by lukehowkins** [comment]
Any update on this?

**Comment by rschristian** [comment]
I can push a release tonight maybe, though the linked issue is still a very real problem that we haven't found an answer for.

**Comment by rschristian** [comment]
Released v4.1.0

Let me know if there are any issues.
