### ISSUE TITLE
🧪 Jest is having trouble finding `Fragment`

### ISSUE THREAD

**Issue by furkanacaryes** [preactjs/jest-preset-preact#7]
I get the error below if I try to render a `<></>` whereas `<Fragment><Fragment />` seems to be working just fine.

```sh
ReferenceError: Fragment is not defined
```

You can access [my template with healthy test](https://github.com/futuredayv/vite-preact/tree/test-example) for re-production. I hope I'm just missing something 🤔

> Note that Typescript version is `^4.2.4` and no custom `.babelrc` is involved.

**Comment by mvarendorff** [comment]
This is caused by this piece here:

https://github.com/preactjs/jest-preset-preact/blob/27ad0023401f2d3072966d279955ce3e6d9d1565/src/babel.js#L3-L10

I am using a custom babel.js because I had trouble with the preset and adding:

```
jsxPragmaFrag: "Fragment",
```
as config to the typescript-preset helped. From the docs of the babel preset:
> Replace the function used when compiling JSX fragment expressions. This is so that we know that the import is not a type import, and should not be removed.

So my assumption is that the typescript preset removed the import making it unavailable for jest. I opened a pull request at #8 :)

**Comment by furkanacaryes** [comment]
@geisterfurz007 Thanks a lot! I've been suspicious about that exact line. I had tried adding that in a `.babelrc` but couldn't figure it out with **Vite** 😅 

Also, it makes me wonder if everyone has been trying to figure out how to render a fragment sugar 🤔

**Comment by furkanacaryes** [comment]
Components using sugar fragment also need to import it just like `h`.

```ts
import { h, Fragment } from 'preact';
```

I thought it would be helpful to note that.

**Comment by timohermans** [comment]
Thanks @futuredayv, this solved my issue ! Any idea if there's any documentation about this?

**Comment by furkanacaryes** [comment]
Sure, [you can check here](https://babeljs.io/docs/en/babel-plugin-transform-typescript#jsxpragmafrag) to understand more clearly why we need to add this to our babel config.

Simply, `jsxPragmaFrag` is set to `React.Fragment` as default, and we need to tell it to use just `Fragment`.

```
jsxPragmaFrag: "Fragment",
```

And for the import, [here's the Fragment usage from the official Preact docs](https://preactjs.com/guide/v10/components#fragments)
